# docker-compose.yml
# https://docs.docker.com/compose/compose-file/compose-file-v2/
---
version: "3"

services:
  webhook:
    build:
      context: .
    restart: unless-stopped
    depends_on:
      - database
    env_file:
      - "service.env"
    ports:
      - 8080:8080
    environment:
      - PORT=8080

  database:
    image: postgres:15-alpine
    restart: unless-stopped
    env_file:
      - "service.env"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 256M

volumes:
  db_data:
